# Generated by Django 4.0.4 on 2023-08-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.ImageField(upload_to='')),
                ('Address', models.TextField()),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], max_length=9)),
            ],
        ),
    ]
