# Generated by Django 4.0.4 on 2023-08-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectNeighbours', '0004_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Profile_Pic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
