# Generated by Django 4.0.4 on 2023-08-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectNeighbours', '0005_person_profile_pic_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
