# Generated by Django 4.0.4 on 2023-08-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectNeighbours', '0007_alter_person_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Profile_Pic',
        ),
    ]
