# Generated by Django 4.0.4 on 2023-08-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectNeighbours', '0008_remove_person_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
